# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-31 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 17, 40, 38, 547308, tzinfo=utc)),
        ),
    ]
