# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170831_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 1, 16, 14, 17, 849138, tzinfo=utc)),
        ),
    ]
